global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'concert-ticketing-backend'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 