version: '3.8'

services:
  backend:
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 2G
      replicas: 3
    environment:
      - SCENARIO=high

  db:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
