version: '3.8'

services:
  backend:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      replicas: 1
    environment:
      - SCENARIO=baseline

  db:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
