version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/concert_db
    networks:
      - backend-net
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=concert_db
    ports:
      - "5432:5432"
    networks:
      - backend-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data: 