version: '3.8'

services:
  backend:
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
      replicas: 5
    environment:
      - SCENARIO=spike

  db:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
