version: '3.8'

services:
  backend:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      replicas: 2
    environment:
      - SCENARIO=medium

  db:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
